import type { ScenarioPreset } from "./types"

export const DEFAULT_PARAMETERS = {
  trafficVolume: 0,
  publicTransport: 0,
  industrialEmissions: 0,
  constructionActivity: 0,
  greenCover: 0,
  roadCapacity: 0,
}

export const SCENARIO_PRESETS: ScenarioPreset[] = [
  {
    id: "reduce_traffic",
    name: "Reduce Traffic",
    icon: "🚗",
    tagline: "Traffic −20%",
    description: "Enact peak-hour low emission corridors, congestion pricing, and freight delivery curfews.",
    color: "#3b82f6",
    parameters: {
      trafficVolume: -20,
      publicTransport: 0,
      industrialEmissions: 0,
      constructionActivity: 0,
      greenCover: 0,
      roadCapacity: 0,
    },
  },
  {
    id: "promote_public_transit",
    name: "Promote Public Transport",
    icon: "🚌",
    tagline: "Transit +25%, Traffic −15%",
    description: "Expand Pune Metro feeder services and PMPML bus electrification with subsidized fares.",
    color: "#06b6d4",
    parameters: {
      trafficVolume: -15,
      publicTransport: 25,
      industrialEmissions: 0,
      constructionActivity: 0,
      greenCover: 0,
      roadCapacity: 0,
    },
  },
  {
    id: "green_city",
    name: "Green City Canopy",
    icon: "🌳",
    tagline: "Green Cover +20%",
    description: "Rapid afforestation along arterial rings, urban bioswales, and mandatory green roofs.",
    color: "#10b981",
    parameters: {
      trafficVolume: 0,
      publicTransport: 0,
      industrialEmissions: 0,
      constructionActivity: 0,
      greenCover: 20,
      roadCapacity: 0,
    },
  },
  {
    id: "reduce_industrial",
    name: "Industrial Pollution Controls",
    icon: "🏭",
    tagline: "Industrial −25%",
    description: "Strict flue gas desulfurization, industrial boiler efficiency norms, and stack scrubbers.",
    color: "#f59e0b",
    parameters: {
      trafficVolume: 0,
      publicTransport: 0,
      industrialEmissions: -25,
      constructionActivity: 0,
      greenCover: 0,
      roadCapacity: 0,
    },
  },
  {
    id: "smart_traffic",
    name: "Smart Traffic Management",
    icon: "🚦",
    tagline: "Traffic −15%, Capacity +10%",
    description: "Adaptive AI signal timing, dynamic lane allocation, and bottleneck clearance.",
    color: "#8b5cf6",
    parameters: {
      trafficVolume: -15,
      publicTransport: 0,
      industrialEmissions: 0,
      constructionActivity: 0,
      greenCover: 0,
      roadCapacity: 10,
    },
  },
  {
    id: "sustainable_city",
    name: "Sustainable City (Comprehensive)",
    icon: "🌱",
    tagline: "Transit +20%, Green +15%, Traffic & Industry −15%",
    description: "Holistic master-plan: synchronized clean mobility, industrial filter mandate, and urban forest belts.",
    color: "#ec4899",
    parameters: {
      trafficVolume: -15,
      publicTransport: 20,
      industrialEmissions: -10,
      constructionActivity: -10,
      greenCover: 15,
      roadCapacity: 5,
    },
  },
]
